### ISSUE TITLE
Log for udp

### ISSUE THREAD

**Issue by seabig6** [danieleteti/loggerpro#11]
Can add logger for udp to debug?
There is useful to debug for mobile.

**Comment by nurettin** [comment]
I made a rfc 5432 based udp logger using this library, it is just a couple of dozen lines of code, I can share it if you want.

**Comment by danieleteti** [comment]
Sure, Great!

**Comment by nurettin** [comment]
@danieleteti  Sorry for double commit, hope that's not a problem.

**Comment by nurettin** [comment]
The packets of this client are going out as plain text. If you open up a public syslog server, people take it upon themselves to spam it with junk. As it stands, this logger is only useful behind a secure network and we need an authorization mechanism such as TCP/TLS.
