### ISSUE TITLE
Minor issue for old delphi - should be "TThread.CurrentThread.ThreadID"

### ISSUE THREAD

**Issue by edwinyzh** [danieleteti/loggerpro#15]
This is an excellent logging library, in that it's easy to understand and use, supporting multi target, and allowing **writing custom appender** (this is a very useful feature).

Just one very minor issue report, under **xe4**,  `TThread.Current.ThreadID` should be `TThread.CurrentThread.ThreadID`.

thanks!

**Comment by danieleteti** [comment]
It should be fixed now. 
The fixed will be in the next release.
