### ISSUE TITLE
NSQueue appender

### ISSUE THREAD

**Issue by Fulgan** [danieleteti/loggerpro#25]
For our project at work I have created a [nsq](https://nsq.io) appender for logger pro. This allow us to collect logs from many different servers in a decentralized way: no central point of failure, local caching of log items, consumers can be added for many different types of messages, etc.

Would it be worthwhile to add this write to loggerPro ?

**Comment by edwinyzh** [comment]
@Fulgan , Yes, please, it looks interesting. I did a quick google search and it didn't reveal any NSQ delphi wrapper, so I guess you had to do it by yourself?

**Comment by danieleteti** [comment]
Great! Will be integrated ASAP.

**Comment by Fulgan** [comment]
I'll need to remove the code that is specific to our own use before I can integrate it but that won't take too long.

**Comment by Fulgan** [comment]
@edwinyzh Actually, the appender is simply a HTTP post to a localhost port so here is really no need for a wrapper.
The consumers are another matter entirely: I use [NSQSharp](https://github.com/judwhite/NsqSharp) wrapper to write ours (In C#)

**Comment by Fulgan** [comment]
Pull request is in.
