### ISSUE TITLE
Speed testing file appender

### ISSUE THREAD

**Issue by mathieson-scott** [danieleteti/loggerpro#26]
Hi,

Using the fileappender demo project, I have add the following code on a button click: 

for i := 1 to 100000 do
  begin
    Log.Debug('Debug message #' + inttostr(i), 'TAG1');
  end;

I have found the resulting file does not contain all 100000 entries. Is there a limit to the speed of writing?

**Comment by mathieson-scott** [comment]
I've found a similar problem. Running the fileappender demo, when I click the Multi-threading button, it does not seem to write all the entries to file. The file will end up with between 1000-2000 or so lines instead of 3200. If I add a Sleep(1) into the anonymous thread procedure, it produces 3200 lines.

**Comment by danieleteti** [comment]
Please, provide a self contained sample.

**Comment by mathieson-scott** [comment]
Do I need to create a repo to do that, or can I attach files here?

**Comment by danieleteti** [comment]
Just attach files here, thanks.

**Comment by danieleteti** [comment]
The project is not compilable (refers to a file on your compouter) and there isn't event handler for the button "Log 100000".

**Comment by danieleteti** [comment]
However, I think to have find the behaviour you talk about.

**Comment by danieleteti** [comment]
Now it should be fixed in the `https://github.com/danieleteti/loggerpro/tree/feature_newthreadedqueue` branch Please do your tests.

**Comment by mathieson-scott** [comment]
Thank you - this has resolved both issues.
