### ISSUE TITLE
Comply with the Apache License

### ISSUE THREAD

**Issue by viertausend** [danieleteti/loggerpro#29]
Hello folks,

I want to use LoggerPro in my Delphi application and first to say thank you for the fantastic work.

There is just one thing I have to know before using it. Is it enough to put the name and the copyright together with the Apache 2.0 license in a textfile which resides in the same folder as the exe file? Or do I have to include the information explicitely in my GUI?

I ask because I evaluating the use in a application which will have a very minimalistic GUI (Console Application).

Thank you!

**Comment by danieleteti** [comment]
Give a look at this https://www.whitesourcesoftware.com/resources/blog/top-10-apache-license-questions-answered/
