### ISSUE TITLE
[suggestion] - Add ability to define log format in VCLMemoAppender

### ISSUE THREAD

**Issue by frankble** [danieleteti/loggerpro#30]
Would it be possible to add a own Logformat definition to the Create Constructor like you did in VCLListViewAppender?
I have to add it every time when i download a actual copy of this repo ;-)

**Comment by danieleteti** [comment]
Hi @frankble could you share what you change in the code? Maybe we could integrate it directly in the framework.

**Comment by frankble** [comment]
Its already done since 4 years ;)

**Comment by danieleteti** [comment]
Arg! Thank you I forgot that :-)
