### ISSUE TITLE
breaking compatibility with Delphi XE3 

### ISSUE THREAD

**Issue by DanieleBarbato** [danieleteti/loggerpro#31]
With version 1.3.0 there is a problem in ThreadSafeQueueU.pas :
E2506 Method of parametrized type declared in interface section must not use local symbol 'cRetryCount'

function is TThreadSafeQueue<T>.Enqueue(const Item: T): Boolean;

![image](https://user-images.githubusercontent.com/45941495/50094736-2da68500-0214-11e9-8a4d-aa0ea25e112c.png)

**Comment by leosurban** [comment]
And XE2 too.
