### ISSUE TITLE
Different LogLevels for one ILogWriter

### ISSUE THREAD

**Issue by guentherchris** [danieleteti/loggerpro#34]
Dear Daniel,

thank you for the great library loggerpro. It is awesome to work with it - I just started to play a litte with the framework. Well done! :-)

I have one question related to the handling of loglevels. Especially when it comes to different appenders in ONE logwriter.  I saw the sample with multiple appenders. 
What I want to understand clearer is the interoperation between ILogWriter and ILogAppender. I learned so far that one can define a loglevel for each appender. This is fine - although I would have expected a range (of loglevels) to which this appender will "forward" the logmessages fired. I solved this by adding the same appenders along with a different loglevel set I would like to have for this appender.

Now to the level of ILogWriter.LogLevel: I wonder why this is needed? Since I already set the loglevels in the appender and I assumed that when I drop a message to level 'warning" for example each added appender would receive the message if the loglevel does match.

Maybe you can help me to understand the concept and what I am missing at the moment?
Would be fine and I am looking forward to your answer.

Thank you again for the great and really useful logging framework.

Best regards,
Chris

**Comment by danieleteti** [comment]
Hi, the LogLevel are progressive. So if you set DEBUG also WARNING, INFO and ERROR are included. If you set WARNING, only WARNING and ERROR are included and so on.

...and sorry for the veery late response...
