### ISSUE TITLE
XE5 support

### ISSUE THREAD

**Issue by IgaziFido** [danieleteti/loggerpro#36]
Hi!
It seems for me, that there is no support for XE5, while the description says, there is. Am I right? I've found packages for XE7 and upper.
Thanks!

**Comment by danieleteti** [comment]
Did you try to install the XE7 package?

**Comment by IgaziFido** [comment]
I will check it.

**Comment by IgaziFido** [comment]
It can be compiled under XE5, only 1 line failes in unit LoggerPro.UDPSyslogAppender, at line 141, DateToISO8601 is not in System.DateUtils.

**Comment by danieleteti** [comment]
We don't have XE5 anymore. Can you fix it and PR the changes?

**Comment by IgaziFido** [comment]
Yes, I'll do it.
