### ISSUE TITLE
There seems to be no info about supported Delphi versions

### ISSUE THREAD

**Issue by Kromster80** [danieleteti/loggerpro#4]
There seems to be no info about supported Delphi versions on the main page or readme.md.

I tried compiling the code in Delphi XE2 and failed:

    if FLogsFolder.IsEmpty then // <<-- this line fails in XE2

> [DCC Error] LoggerPro.FileAppender.pas(126): E2018 Record, object or class type required
> [DCC Fatal Error] LoggerPro.pas(230): F2063 Could not compile used unit 'LoggerPro.FileAppender.pas'

**Comment by danieleteti** [comment]
I dont have XE2 anymore. Try to change it in 
`if FLogsFolder = '' then`
and see what happens.

**Comment by Kromster80** [comment]
Sure, that helps (this and several more places) and LoggerPro starts to work under Delphi XE2.

I see one or two things to do now
 - Add version requirements into readme.md
 - Optionally - change code to work on XE2 (and/or possibly on earlier versions)

**Comment by danieleteti** [comment]
Ok, I'll change the "String.IsEmpty" in " = '' "

**Comment by Kromster80** [comment]
Also line 324 in LoggerPro.pas

    if TObject(FLogAppenders[I]).ClassName.Equals(AppenderName) then
to
    if SameText(TObject(FLogAppenders[I]).ClassName, AppenderName) then

Sorry I could not make a pull request at the time. These 2 changes are enough to make it work in XE2.

P.S. Thank you for quick response!

**Comment by danieleteti** [comment]
All the changes has been included in the new RC5 build. Update the repo and test it please.

**Comment by Kromster80** [comment]
Seems to work well now. Thanks!
