### ISSUE TITLE
Is a log file viewer planned?

### ISSUE THREAD

**Issue by darianmiller** [danieleteti/loggerpro#41]
One of the best features that I'm missing from SmartInspect is the log file viewer...curious if there are plans to add a viewer here.

**Comment by epachsoft** [comment]
Now days with specialized distributed logger aggregators like elastic search (Kibana), GrayLog, Grafana, Splunk and others the time of single file log viewers is over.  I was a SmartInspect user and then I switched to QuickLogger, they had a nice visualizer but it was not scaling well for big files, forget about multiple sources, graphics or visualizations.

**Comment by danieleteti** [comment]
When using plain text files, we use [BareTail](https://www.baremetalsoft.com/baretail/).
With LoggerPro you can append your logs everywhere. Did you tried Redis and the Redis Viewer?

**Comment by darianmiller** [comment]
@epachsoft There's a very long way to go before log file viewers are irrelevant.  I see the obvious trend though.
@danieleteti I'll take a look at BareTail.  Thanks.
