### ISSUE TITLE
多个程序同时往一个文件中写如何解决

### ISSUE THREAD

**Issue by defutian** [danieleteti/loggerpro#42]
启动多个程序使用TLoggerProFileAppender同时写日志，将会出现文件被占用、文件备份等错误，请问应该如何解决？

**Comment by danieleteti** [comment]
Please, use english (even google translate version is OK).
Original question was: 
```
If you start multiple programs and use TLoggerProFileAppender to write logs at the same time, there will be errors such as file occupation and file backup. What should I do?
```
Use the "Include PID" in the TLoggerProFileAppended so that the logs will be splitted by PID.
