### ISSUE TITLE
Bug in constructor TLoggerProUDPSyslogPacket.Create(pLogItem: TLogItem; pHostName: string; pUserName: string;   pApplication: string; pVersion: string; pProcID: string; pUnixLineBreaks: Boolean; pUTF8BOM: Boolean);

### ISSUE THREAD

**Issue by Lajos-Juhasz** [danieleteti/loggerpro#50]
constructor TLoggerProUDPSyslogPacket.Create(pLogItem: TLogItem; pHostName: string; pUserName: string;
  pApplication: string; pVersion: string; pProcID: string; pUnixLineBreaks: Boolean; pUTF8BOM: Boolean);

If pUnixLineBreaks is false the logger doesn't sends the LogMessage. Currently:

 if FUnixLineBreaks then
    FMessageData := pLogItem.LogMessage.Replace(sLineBreak, '#10', [rfReplaceAll]);

Should be:

  if FUnixLineBreaks then
    FMessageData := pLogItem.LogMessage.Replace(sLineBreak, '#10', [rfReplaceAll])
  else
    FMessageData :=  pLogItem.LogMessage;

**Comment by danieleteti** [comment]
Thank you, fixed

**Comment by nurettin** [comment]
Sorry that was on me, I didn't want to update the code without testing since I don't use delphi anymore.
