### ISSUE TITLE
GetCurrentProcessID is only for windows

### ISSUE THREAD

**Issue by seabig6** [danieleteti/loggerpro#6]
function TLoggerProFileAppender.GetLogFileName
line 104：``` lFormat := '.PID-' + IntToStr(GetCurrentProcessID) + lFormat;```
function GetCurrentProcessID is only for windows!

**Comment by danieleteti** [comment]
Where do you want to use the logger?

**Comment by seabig6** [comment]
Android.

**Comment by seabig6** [comment]
Thanks a lot!
