### ISSUE TITLE
MaxBackupFileCount always equal 1

### ISSUE THREAD

**Issue by zinpub** [danieleteti/loggerpro#61]
Maybe must be Max?

constructor TLoggerProFileAppenderBase.Create(aMaxBackupFileCount: Integer; aMaxFileSizeInKiloByte: Integer; aLogsFolder: string;
  aFileAppenderOptions: TFileAppenderOptions; aLogFileNameFormat: string; aLogFormat: string; aEncoding: TEncoding);
begin
  inherited Create(ALogFormat);
  fLogsFolder := aLogsFolder;  
  fMaxBackupFileCount:= **Min**(1, aMaxBackupFileCount);
  fMaxFileSizeInKiloByte := aMaxFileSizeInKiloByte;
  fLogFileNameFormat := aLogFileNameFormat;

**Comment by luebbe** [comment]
You're obviously right. This is a result of #60 where I wrote wrong example code.
