### ISSUE TITLE
Feature Request for low level Windows Event logger

### ISSUE THREAD

**Issue by HealthOneNZ** [danieleteti/loggerpro#63]
The current implementation requires a TService instance to be passed to the constructor of TLoggerProWindowsEventLogAppender 

This limits the use of the logger to service applications. 

I've written a unit which allows the service name (or a proxy of that) to be passed as plain text and a separate instance of the low level windows event logger is created.

Happy to share this code with the project.  Usage is is simple as

`   var SIEMLog: ILogWriter;
...
   SIEMLog := BuildLogWriter([TLoggerProWindowsEventLogAppenderLL.Create('TheServiceName")]);
...
   SIEMLog.Debug('This is a test message');`

``

**Comment by danieleteti** [comment]
Would be great.
Feel free to provide a PR with your new Appender

**Comment by danieleteti** [comment]
Any news?

**Comment by fastbike** [comment]
We're using the innards of the TService windows event logger, but are having some stability issues which we are working through.
