### ISSUE TITLE
Adding Date to fileappender filename

### ISSUE THREAD

**Issue by jfudickar** [danieleteti/loggerpro#66]
Hi,
I would like to see an option to add the current date to the fileappender.
Do you thinks this is helpfull?

Should I create a first implementation and add it as a pull request?
If yes, I would enhance the TLoggerProFileAppenderBase class. Maybe by adding only TFileAppenderOption.

Regards
Jens

**Comment by danieleteti** [comment]
Yes, it may be useful.
Feel free to provide a PR
