### ISSUE TITLE
FileAppender write in the wrong position.

### ISSUE THREAD

**Issue by TikoTako** [danieleteti/loggerpro#72]
Hello,
i have a global ILogWriter that is called from the dpr and from a main unit.
Before the program close i have one last debug write on the dpr, when that happens it write back in the last position it had on the last write (done in the dpr), so it overwrite some of the log done while in the main unit.

**Comment by danieleteti** [comment]
Can you reproduce the error please?

**Comment by TikoTako** [comment]
> Can you reproduce the error please?

Here:
https://github.com/TikoTako/loggerpro-test

**Comment by luebbe** [comment]
I have seen this offset sometimes as well, but never took a closer look. I attributed it to two instances of the application running in parallel and writing into the same log file (when the PID is not used in the file name). But @TikoTako 's log shows that it is obviously written from the same thread.

**Comment by danieleteti** [comment]
I deeply investigated the problem (I never seen it in years).The problem is the file name format. 
When you pass a filenameformate which doesn't contain placeholders, the filename is not deparated by TAG and all writers writes on the same file. The problem is that current code doesn't check this situation. I added the following check in `function TLoggerProFileAppenderBase.GetLogFileName(const aTag: string; const aFileNumber: Integer): string;`


```delphi
function TLoggerProFileAppenderBase.GetLogFileName(const aTag: string; const aFileNumber: Integer): string;
var
  lExt: string;
  lModuleName: string;
  lPath: string;
  lFormat: string;
begin
{$IF Defined(Android)}
  lModuleName := TAndroidHelper.ApplicationTitle.Replace(' ', '_', [rfReplaceAll]);
{$ENDIF}
{$IF not Defined(Mobile)}
  lModuleName := TPath.GetFileNameWithoutExtension(GetModuleName(HInstance));
{$ENDIF}
{$IF Defined(IOS)}
  raise Exception.Create('Platform not supported');
{$ENDIF}
  lFormat := fLogFileNameFormat;

  if TFileAppenderOption.IncludePID in fFileAppenderOptions then
    lModuleName := lModuleName + '_pid_' + IntToStr(CurrentProcessId).PadLeft(6, '0');

  lPath := fLogsFolder;
  lExt := Format(lFormat, [lModuleName, aFileNumber, aTag]);
  if lExt = lFormat then { means that lFormat doesn't contain place holders }
  begin
    raise ELoggerPro.CreateFmt(
      'Wrong FileName Format "%s". [HINT: Placeholders in template_filename are required. Just as an example, the DEFAULT_FILENAME_FORMAT is "%s"]',
      [lFormat, DEFAULT_FILENAME_FORMAT]);
  end;
  Result := TPath.Combine(lPath, lExt);
end;

```

**Comment by TikoTako** [comment]
With TLoggerProSimpleFileAppender and one file the order is correct, also is ok with TLoggerProFileAppender if it use different log files (one each unit)
