### ISSUE TITLE
Only one backup file ever used

### ISSUE THREAD

**Issue by FixzoneBrian** [danieleteti/loggerpro#73]
Found a problem with the backup files it is only ever using 1 backup file regardless of what you set the MaxBackupFileCount to 
In LoggerPro.FileAppender create it has
fMaxBackupFileCount:= Min(1, aMaxBackupFileCount);

**Comment by luebbe** [comment]
Which version are you using? this is a duplicate of #61 and should already be fixed since a while.

**Comment by FixzoneBrian** [comment]
It's version 1.4.3
