### ISSUE TITLE
Enabling appenders feature request

### ISSUE THREAD

**Issue by SirRigorMortis** [danieleteti/loggerpro#76]
TLoggerProAppenderBase FEnabled declared as private and seems never used. Please add feature to enable/disable selected appender or all appenders at once.

**Comment by danieleteti** [comment]
Please, check branch "76-enabling-appenders-feature-request".
So far only the file appenders have been updated. Does this implementation works for you?

**Comment by danieleteti** [comment]
news?

**Comment by danieleteti** [comment]
news?

**Comment by Basti-Fantasti** [comment]
I have implemented a wrapper on which only the desired Log Appenders are configured and added to the list of appenders. This works for me. But being able to enable/disable appenders in the running process could be useful.
