### ISSUE TITLE
why not fatal error level log?

### ISSUE THREAD

**Issue by chinghoitam** [danieleteti/loggerpro#80]
Excuse me, Why is there no fatal error level?

**Comment by danieleteti** [comment]
No particular reason. We can plan to add it.

**Comment by luebbe** [comment]
Very nice. I wanted to suggest the same for exeption logging.

**Comment by danieleteti** [comment]
@luebbe regarding exceptions I've different feeling. What's the "log level" of an exception? There are fatal exceptions and "normal" exceptions (user wrote "a" in a number only field). So, while is very simple to implement I really don't have a crear vision about it.

**Comment by luebbe** [comment]
Of course. Not every exception is fatal. Our "well handled" exceptions only have debug or info level if they are logged at all. I was more thinking about the catastrophic ones.
